### ISSUE TITLE
Maven repositories for Spring Boot already present

### ISSUE THREAD

**Issue by jbrannst** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-guides#25]
After building the app in step 3 in Break Monolith Apart - II, I get 

> ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [FATAL] Non-parseable POM /projects/cloud-native-workshop-v2m1-labs/catalog/pom.xml: Duplicated tag: 'repositories' (position: START_TAG seen ...</profiles>\n  <repositories>... @236:17)  @ line 236, column 17
>  @ 
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]   
> [ERROR]   The project  (/projects/cloud-native-workshop-v2m1-labs/catalog/pom.xml) has 1 error
> [ERROR]     Non-parseable POM /projects/cloud-native-workshop-v2m1-labs/catalog/pom.xml: Duplicated tag: 'repositories' (position: START_TAG seen ...</profiles>\n  <repositories>... @236:17)  @ line 236, column 17 -> [Help 2]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
> [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException
> 

This is because the repository definitions are already provided as part of the source code, injected at the bottom of the POM file. 

Either remove the instructions to add the repositories from the guide or from the supplied _pom.xml_ file.

**Comment by danieloh30** [comment]
Good point. It meant to be added in pom.xml. I removed unnecessary instruction.
