### ISSUE TITLE
Step 6: Test the build - image is wrong

### ISSUE THREAD

**Issue by mandibuswell** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-guides#30]
the image in step 6 is the same as step 4, this could be confusing - it would be better if this was the image for the actual step.

####6. Test the build

Build and package the app using Maven to make sure you code still compiles via CodeReady Workspaces BUILD window:

![rhamt_project_issues]({% image_path codeready-workspace-build.png %})

**Comment by mandibuswell** [comment]
![Screenshot from 2020-02-17 23-57-41](https://user-images.githubusercontent.com/12392607/74649028-a7088180-51e3-11ea-84dd-c57c286f4c2a.png)

**Comment by mandibuswell** [comment]
same issue in step 10

**Comment by danieloh30** [comment]
We've already improved them in the next CCN release based OCP 4.3(WIP). Thank you for your contribution.
