### ISSUE TITLE
Error when click 'open report' from "Migrate to JBoss EAP"/2.View Detials about the migration issues

### ISSUE THREAD

**Issue by piggyvenus** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-guides#41]
When right-clicking to 'Open Report' from one of the hints in MTA, I got an error and not the Source report. Am I missing steps? or click at the wrong spot?
![Screen Shot 2021-04-01 at 4 38 31 PM](https://user-images.githubusercontent.com/15617833/113364645-ec651100-9308-11eb-8c10-12535394b85f.png)

**Comment by danieloh30** [comment]
This is a known issue on the latest MTA on OCP 4.7.

https://issues.redhat.com/browse/WINDUP-3048

If you want to run a customer event, you need to use the stable cluster on OCP 4.5.
