### ISSUE TITLE
Migrate to JBoss EAP - issue opening MTA file report from CRW

### ISSUE THREAD

**Issue by gbengataylor** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-guides#43]
Attempted to follow this instruction
```
MTA also provides helpful links to understand the issue deeper and offer guidance for the migration when you click on Open Report:
```
![image](https://user-images.githubusercontent.com/30447678/113763836-273fbe00-96e8-11eb-83f3-3b13e123b1c7.png)

However, CRW takes you to a non-existent page
<ocp_url>/home/theia/output/0p45rc4r0-khveteorx/reports/StartupListener_java.html

![image](https://user-images.githubusercontent.com/30447678/113763943-4b9b9a80-96e8-11eb-83b5-526ccf5dba77.png)

The right link is 
<ocp_url>/0p45rc4r0-khveteorx/reports/StartupListener_java.html

This is more of a CRW bug than with the Workshop bug but maybe we can update the instructions so that the Attendees don't run into this problem

**Comment by danieloh30** [comment]
As I mentioned earlier in the email thread, this is a known issue(https://issues.redhat.com/browse/WINDUP-3048) that the MTA eng team is working on it.

**Comment by gbengataylor** [comment]
oops, sorry about that. totally missed that message

**Comment by danieloh30** [comment]
No worries. Please keep doing the test as well as monitoring the cluster status when you go through M3.
