### ISSUE TITLE
Break Monolith Apart - 1: Screenshot for 5005 and 8080 incorrect after initial deploy of inventory services

### ISSUE THREAD

**Issue by gbengataylor** [RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-guides#44]
![image](https://user-images.githubusercontent.com/30447678/113795552-3429d500-971b-11eb-8850-751937b33560.png)

Then select

![image](https://user-images.githubusercontent.com/30447678/113795615-528fd080-971b-11eb-85aa-6e27014dbd5f.png)

**Comment by danieloh30** [comment]
Good catch. It's changed in CRW 2.7. Can you create a PR for this in ocp-4.7 branch? You need to create multiple PRs for each module since this image is used in all modules. 

Once the PRs are merged, I will close this issue.

**Comment by gbengataylor** [comment]
will do! plan to create PRs for any issues I create once I'm done with all the modules

**Comment by danieloh30** [comment]
Thanks. Be sure to adjust the image size along with the original one.

**Comment by danieloh30** [comment]
PR is merged
